name: cat_trivia_app
description: Cat facts project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  dio: ^5.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  pretty_dio_logger: ^1.3.1
  http: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/cat_trivia_app_background.jpg
    - assets/images/cat_trivia_app_history_background.jpg
